name: Build ARMv6 for NextPi2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
build-armv6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: arm1176
          base_image: raspios_lite:2024-11-19
          image_additional_mb: 512
          copy_artifact_path: pasta
          commands: |
            apt-get update
            apt-get install -y --no-install-recommends fpc
            fpc -dNEXTPI -opasta pasta.pas
      - uses: actions/upload-artifact@v4
        with:
          name: pasta-armv6
          path: pasta