name: Build ARMv6 for NextPi2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build natively in ARM environment
        uses: pguyot/arm-runner-action@v2
        with:
          cpu: arm1176
          image_additional_mb: 512
          commands: |
            apt-get update
            apt-get install -y --no-install-recommends fpc
            fpc pasta.pas

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pasta80
          path: pasta80