name: Build ARMv6 for NextPi2

on:
  push:
    branches: [ nextpi ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build natively in ARM environment
        uses: pguyot/arm-runner-action@v2
        with:
          cpu: arm1176
          image_additional_mb: 512
          copy_artifact_path: pasta
          commands: |
            apt-get update
            apt-get install -y --no-install-recommends fpc
            fpc pasta.pas

      - name: Find binary
        run: find . -name "pasta" -type f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pasta-armv6
          path: pasta

  build-sjasmplus-armv6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sjasmplus with static Lua in ARM environment
        uses: pguyot/arm-runner-action@v2
        with:
          cpu: arm1176
          image_additional_mb: 1024
          copy_artifact_path: sjasmplus/build/release/sjasmplus
          commands: |
            apt-get update
            apt-get install -y --no-install-recommends \
                git cmake make g++ liblua5.4-dev
            git clone --recursive https://github.com/z00m128/sjasmplus.git
            cd sjasmplus
            cmake \
                -DUSE_LUA=1 \
                -DLUA_LIBRARY=/usr/lib/arm-linux-gnueabihf/liblua5.4.a \
                -DLUA_INCLUDE_DIR=/usr/include/lua5.4
            make

      - name: Find binary
        run: find . -name "sjasmplus" -type f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sjasmplus-armv6-lua
          path: sjasmplus/build/release/sjasmplus